### ISSUE TITLE
Cant load the spawn egg with EntityTag 

### ISSUE THREAD

**Issue by haiman233** [NCBPFluffyBear/SlimeCustomizer#35]
## Description (Required)
Cant load the spawn egg with EntityTag
it‘s a saveditem
## Steps to reproduce the Issue (Required)
Hold the spawn_egg with {EntityTag:{id:"minecraft:tnt"}} and save the items. After adjusting the configuration, restart the server and display the following error

## Expected behavior (Required)
Unable to load the configuration file with the following error

## Server Log / Error Report
[10:29:57 ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_18_R2.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[10:30:01 ERROR]: Error occurred while enabling SlimeCustomizer vDEV - 25 (git 4435082d) (Is it up to date?)
[10:30:01 ERROR]: Suspected Plugins: 
[10:30:01 ERROR]:       SlimeCustomizer{enabled,ver=DEV - 25 (git 4435082d),path=plugins/SlimeCustomizer-25.jar}
[10:30:01 ERROR]:       Slimefun{enabled,ver=1.2.4,path=plugins/SlimefunOptimized-v1.2.4.jar}
[10:30:01 ERROR]: Exception details below: 
java.lang.IllegalArgumentException: The ItemMeta cannot be null!
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[commons-lang-2.6.jar:2.6]
        at io.github.thebusybiscuit.slimefun4.core.services.CustomItemDataService.setItemData(CustomItemDataService.java:85) ~[SlimefunOptimized-v1.2.4.jar:?]
        at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItemStack.<init>(SlimefunItemStack.java:66) ~[SlimefunOptimized-v1.2.4.jar:?]
        at io.ncbpfluffybear.slimecustomizer.registration.Items.register(Items.java:83) ~[SlimeCustomizer-25.jar:?]
        at io.ncbpfluffybear.slimecustomizer.SlimeCustomizer.onEnable(SlimeCustomizer.java:124) ~[SlimeCustomizer-25.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patina-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patina-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[patina-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[patina-1.18.2.jar:git-Paper-"c949a0d"]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[patina-1.18.2.jar:git-Paper-"c949a0d"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[patina-1.18.2.jar:git-Paper-"c949a0d"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[patina-1.18.2.jar:git-Paper-"c949a0d"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:336) ~[patina-1.18.2.jar:git-Paper-"c949a0d"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1168) ~[patina-1.18.2.jar:git-Paper-"c949a0d"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[patina-1.18.2.jar:git-Paper-"c949a0d"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

## Config Files
[yml.zip](https://github.com/NCBPFluffyBear/SlimeCustomizer/files/8549906/yml.zip)

## Environment (Required)

 - Minecraft Version: 1.18.2
 - CS-CoreLib Version: NONE
 - Slimefun Version: RC-31
 - Plugin Version: DEV -25

**Comment by NCBPFluffyBear** [comment]
Can you send me your saved item yml file? It will be located at `\plugins\SlimeCustomizer\saveditems\`

**Comment by NCBPFluffyBear** [comment]
Oops wrong button

**Comment by haiman233** [comment]
the saved item yml file is at the issue Config Files yml.zip

**Comment by NCBPFluffyBear** [comment]
It looks like there's some issue with the internal tag, but I haven't seen it before. I also don't have that error when I boot...

Do you have any idea what is being stored in this internal data?

**Comment by haiman233** [comment]
I will provide my item configuration and saveditem configuration

**Comment by haiman233** [comment]
I test it ,only the spawn_egg has this issue
![0U3 $BTYTCP366KNY$VQ@LF](https://user-images.githubusercontent.com/83174104/165114783-6e99327b-ebae-4eb2-8e1a-a8f1561da552.png)
e

**Comment by NCBPFluffyBear** [comment]
What does the spawn egg actually do? Does it just spawn a mooshroom cow with TNT蛋 (In red and bold) as the name? How did you initially obtain the egg?

**Comment by haiman233** [comment]
the command is /give ID creeper_spawn_egg{EntityTag:{id:"minecraft:tnt"}}

**Comment by NCBPFluffyBear** [comment]
It looks to be an issue with Slimefun serializing/restoring items. Can you try placing the egg in a Slimefun backpack, restarting the server, and checking if the egg is still in the backpack? I was able to replicate your issue by doing this.

If this problem exists for you for Slimefun as well, please open a bug report on their GitHub.

**Comment by haiman233** [comment]
I place the egg in a backpack,when i restart the serve it is disappear,i will send the issue to the Slimefun4

**Comment by NCBPFluffyBear** [comment]
Closing issue since it should automatically be fixed if fixed on Slimefun's side (Item serialization).
